version: "1" # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 9
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 9
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 35
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true
exclude_patterns:
  - "src/serviceWorker.ts"