/**
 * Defines components for terms and conditions
 */

/**
 * Carriage Crossing Pharmacy Booker
 * Copyright (C) 2020 Luke Zhang, Ethan Lim
 * 
 * https://luke-zhang-04.github.io/
 * https://github.com/ethanlim04
 * This program is free software: you can redistribute it and/or modif
 * it under the terms of the GNU General Public License as published b
 * the Free Software Foundation, either version 3 of the License, o
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be usefu
 * but WITHOUT ANY WARRANTY; without even the implied warranty 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See t
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public Licen
 * 
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import React from "react";

const Legal = () => {
    return (
        <div className='container'>
            <h1>Pharmasave Carriage Crossing Pharmacy Booker Terms of Use</h1>
            <p>Copyright (C) 2020 <a href="https://luke-zhang-04.github.io/">Luke Zhang</a>, <a href="https://github.com/ethanlim04">Ethan Lim</a>, and Pharmasave Carriage Crossing Pharmacy</p>
            <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License (below) for more details.</p>
            <iframe title="GNU General Public License" src="gpl.pdf" style={{width: "100%", height: "80vh"}}></iframe>
            <h1>Important Sections</h1>
            <h2>Disclaimer of Warranty</h2>
            <p>Section 15 of the GNU General Public License</p>
            <p>THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.</p>
            <h2>Limitation of Warranty</h2>
            <p>Section 16 of the GNU General Public License</p>
            <p>IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MOD-IFIES AND/OR CONVEYS THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <h1>Additional</h1>
            <h2>ACCESS TO PRESCRIPTIONS, PRESCRIPTION HISTORY AND OTHER PERSONAL INFORMATION</h2>
            <p>Through the Services, you may be able to access your prescription history and other personal health information that has been collected and generated by your pharmacist. You may also use the Services to request a refill of your prescription from your Pharmasave pharmacy. Access to your personal information is being provided for general informational and record-keeping purposes, to permit you to request a refill and to permit you to provide your personal health information to physicians and other health care professionals and for intervention by your pharmacist to offer certain patient services. The personal information that you can access does not, nor is it intended to be construed as, medical, legal, or other professional advice or opinion or represent your comprehensive or complete medical history. By using the Services to manage your prescriptions and other personal information, you acknowledge and accept the risk that such information will be accessed without your consent, including due to flaws in the security of the device you use to access the Services. By using any of the Services for a person other than yourself, you represent and warrant that you have all necessary consent and authority to do so.
            <br/><br/>    
            If you have a question or concern regarding your prescription, please contact your physician or pharmacist.
            <br/><br/>
            In addition to any regulatory restrictions that may apply, pharmacists reserve the right to refuse prescriptions at their professional discretion and under the direction of policies and rules of the applicable college of pharmacists, prescriber authority and applicable law.</p>
            <h2>INDEMNIFICATION</h2>
            <p>You agree to defend, indemnify and hold harmless each of Pharmasave Drugs (National) Ltd., its affiliates (including the Pharmasave Affiliates) and officers, directors, employees, agents, representatives of the foregoing and all service providers of the foregoing, including all third parties mentioned on or in any way involved in providing any of the Services, from and against any and all claims, actions or demands, including without limitation reasonable legal and accounting fees, resulting from or related to: (a) your breach of these Terms; (b) your access to, use of or reliance upon the Services, your personal information that is accessible through the Services, or the Content of the Services; or (c) your infringement of any intellectual property or privacy rights of any person.</p>
            <h2>MEDICAL DISCLAIMER</h2>
            <p>The Services provide a variety of information and links related to health, fitness and medical products and permits you to register to receive a variety of information. THE CONTENT PROVIDED ON OR BY THE SERVICES IS NOT INTENDED TO TAKE THE PLACE OF YOUR DOCTOR, PHARMACIST, OTHER HEALTH CARE PROFESSIONAL OR ANY INFORMATION CONTAINED ON OR IN ANY PRODUCT PACKAGING OR LABELS. YOU SHOULD NOT USE THE CONTENT TO PRESCRIBE A MEDICATION, OR DIAGNOSE, TREAT, CURE, OR PREVENT ANY DISEASE. Pharmasave does not recommend or endorse any specific tests, products, procedures, opinions or other information that may be mentioned on the Services. When using any information and articles provided by the Services for any purpose, we advise you to consult a qualified professional to verify accuracy and application to you.</p>
        </div>
    );
}

export default Legal;
