name: build

on:
  push:
    branches: [ master, calendar ]
  pull_request:
    branches: [ master, calendar ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm i firebase-functions
    - run: yarn build
      env:
        CI: false
    