name: tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test-app:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout repo
                uses: actions/checkout@v2
            -   uses: actions/setup-node@v1
                with:
                    node-version: 12
            -   run: npm ci
            -   run: yarn test
            