name: stylelint

on:
  push:
    branches: [ master, calendar ]
  pull_request:
    branches: [ master, calendar ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm run-script stylelint
    